export default [
  {
    title: 'FAAP MODA',
    url: 'faap-moda/23.jpg',
    path: 'faap-moda',
    images: [
      [1],
      [2, 3, 4, 5, 6, 7],
      [8],
      [9, 10],
      [11],
      [12, 13],
      [14],
      [15, 16],
      [17],
      [18, 19],
      [20],
      [21],
      [22],
      [23],
      [24],
    ],
    description: '<p>This project was developed as part of an annual contest run by my university - Fundação Armando Álvares Penteado (FAAP). To participate, students submit their projects and six of them are selected and supported to develop and present their collections on a runway show judged by some of the most relevant professionals in the fashion industry.</p><p>My collection was inspired by the symbology whimsicality of the Japanese animations directed by Hayao Miyazaki, particularly Spirited Away, Princess Mononoke and Howl\'s Moving Castle. </p>'
  },
  {
    title: 'OS CARAS',
    url: 'os-caras/11.jpg',
    path: 'os-caras',
    images: [
      [1],
      [2, 3, 4, 5, 6, 7],
      [8],
      [9],
      [10],
      [11],
    ],
    description: '<p>\'Os Caras\' is a short film produced as a final graduation project for a group of students in the Cinema course at FAAP. I was invited to work as a costume designer for this story that happens in the 1980s while the population in Brazil grew restless with the political situation and went to the streets demanding direct presidential elections.</p>',
  },
  {
    title: 'PHOTOGRAPHY',
    url: 'photography/7.jpg',
    position: 'top',
    path: 'photography',
    images: [
      [1, 2],
      [3],
      [4, 5],
      [6, 7],
      [8, 9],
    ]
  },
  {
    title: 'ILLUSTRATION',
    url: 'negra.jpg',
    path: 'illustration',
    images: [
      [1, 2],
      [3],
      [4],
      [5],
      [6],
      [7],
      [8],
      [9, 10, 11],
      [12],
    ]
  },
  {
    title: 'PATTERN DESIGN',
    url: 'pattern/9.jpg',
    path: 'pattern',
    images: [
      [1],
      [2],
      [3],
      [4],
      [5],
      [6],
      [7],
      [8],
      [9],
      [10],
      [11],
    ]
  },
];